# Generated by Django 5.2.15 on 2026-06-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('nota', models.FloatField(default=0.0, verbose_name='Média')),
            ],
        ),
    ]
